### ISSUE TITLE
Add more resources to github provider

### ISSUE THREAD

**Issue by AtzeDeVries** [coopnorge/provider-github#9]
```[tasklist]
### Tasks
- [ ] https://github.com/coopnorge/provider-github/issues/10
- [ ] https://github.com/coopnorge/provider-github/issues/11
- [ ] https://github.com/coopnorge/provider-github/issues/12
```
